// All user-facing text lives here, German first. Rank titles (later slices)
// stay German in both languages by design.

export const DEFAULT_LANG = 'de';
export const LANGS = ['de', 'en'];

const tables = {
  de: {
    title: 'KAISER',
    tagline: 'EIN SPIEL UM MACHT UND KORN',
    year: 'ANNO {year}',
    panel_ruler: 'HERRSCHER',
    panel_granary: 'KORNSPEICHER',
    panel_land: 'LÄNDEREIEN',
    panel_people: 'VOLK',
    panel_rations: 'VERPFLEGUNG',
    stat_age: 'ALTER: {age} JAHRE',
    stat_grain: '{grain} FASS KORN',
    stat_land: '{land} MORGEN',
    stat_cultivable: 'BESTELLBAR: {cultivated} MORGEN',
    stat_fallow: 'BRACH: {fallow} MORGEN',
    stat_population: '{population} UNTERTANEN',
    ration_hunger: 'HUNGERRATION',
    ration_knapp: 'KNAPPE RATION',
    ration_gut: 'GUTE RATION',
    ration_fest: 'FESTMAHL',
    ration_cost: 'BEDARF: ≈ {cost} FASS KORN',
    ration_growth: 'ZULAUF: {pct}',
    end_year: 'JAHR BEENDEN [ENTER]',
    hints: '←/→ WÄHLEN · ENTER JAHR BEENDEN · LEER ÜBERSPRINGEN · L SPRACHE · C BILDRÖHRE',
    hints_chronicle: 'LEER ÜBERSPRINGEN · ENTER WEITER',
    chronicle_title: 'CHRONIK · ANNO {year}',
    continue: 'WEITER MIT ENTER',
    weather_catastrophic: 'katastrophal',
    weather_poor: 'mager',
    weather_average: 'durchschnittlich',
    weather_good: 'gut',
    weather_bumper: 'prächtig',
    ch_harvest: 'Das Wetter war {weather}. {cultivated} Morgen wurden bestellt, {fallow} Morgen lagen brach.',
    ch_harvest_yield: 'Die Ernte brachte {harvest} Fass Korn ein.',
    ch_feed: 'Das Volk erhielt {ration}: {eaten} Fass Korn wurden verzehrt.',
    ch_starve: '{deaths} Untertanen sind elend verhungert. Der Schatzmeister weint.',
    ch_growth_up: '{growth} neue Untertanen siedelten sich an.',
    ch_growth_down: '{loss} Untertanen verließen murrend Eure Ländereien.',
    ch_aging: 'Ihr seid nun {age} Jahre alt.',
    ch_death: '{name} starb im Alter von {age} Jahren — ungekrönt und unbeweint.',
    end_title: 'DAS ENDE',
    end_body: '{name} starb Anno {year} im Alter von {age} Jahren, ohne je die Kaiserkrone zu tragen. Die Chronik endet nach {years} Jahren Herrschaft.',
    new_game: 'NEUES SPIEL MIT ENTER',
  },
  en: {
    title: 'KAISER',
    tagline: 'A GAME OF POWER AND GRAIN',
    year: 'ANNO {year}',
    panel_ruler: 'RULER',
    panel_granary: 'GRANARY',
    panel_land: 'ESTATES',
    panel_people: 'PEOPLE',
    panel_rations: 'RATIONS',
    stat_age: 'AGE: {age} YEARS',
    stat_grain: '{grain} BARRELS OF GRAIN',
    stat_land: '{land} MORGEN',
    stat_cultivable: 'CULTIVABLE: {cultivated} MORGEN',
    stat_fallow: 'FALLOW: {fallow} MORGEN',
    stat_population: '{population} SUBJECTS',
    ration_hunger: 'STARVATION RATION',
    ration_knapp: 'MEAGER RATION',
    ration_gut: 'GOOD RATION',
    ration_fest: 'FEAST',
    ration_cost: 'NEEDED: ≈ {cost} BARRELS',
    ration_growth: 'INFLUX: {pct}',
    end_year: 'END THE YEAR [ENTER]',
    hints: '←/→ SELECT · ENTER END YEAR · SPACE SKIP · L LANGUAGE · C CRT',
    hints_chronicle: 'SPACE SKIP · ENTER CONTINUE',
    chronicle_title: 'CHRONICLE · ANNO {year}',
    continue: 'CONTINUE WITH ENTER',
    weather_catastrophic: 'catastrophic',
    weather_poor: 'poor',
    weather_average: 'average',
    weather_good: 'good',
    weather_bumper: 'magnificent',
    ch_harvest: 'The weather was {weather}. {cultivated} Morgen were cultivated, {fallow} Morgen lay fallow.',
    ch_harvest_yield: 'The harvest brought in {harvest} barrels of grain.',
    ch_feed: 'The people received the {ration}: {eaten} barrels of grain were consumed.',
    ch_starve: '{deaths} subjects starved miserably. Your treasurer weeps.',
    ch_growth_up: '{growth} new subjects settled in your lands.',
    ch_growth_down: '{loss} subjects left your lands, grumbling.',
    ch_aging: 'You are now {age} years old.',
    ch_death: '{name} died at the age of {age} — uncrowned and unmourned.',
    end_title: 'THE END',
    end_body: '{name} died in anno {year} at the age of {age}, never having worn the imperial crown. The chronicle ends after {years} years of rule.',
    new_game: 'NEW GAME WITH ENTER',
  },
};

export function getString(lang, key, params = {}) {
  const raw = tables[lang]?.[key] ?? tables[DEFAULT_LANG][key] ?? key;
  return raw.replace(/\{(\w+)\}/g, (_, k) => (params[k] !== undefined ? params[k] : `{${k}}`));
}
